"""添加 need_change_password 字段

Revision ID: 7b2d43f224c1
Revises: 
Create Date: 2026-04-22 12:22:14.875955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b2d43f224c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_crawler_type', table_name='user_crawler_configs')
    op.drop_index('idx_status', table_name='user_crawler_configs')
    op.drop_index('idx_user_id', table_name='user_crawler_configs')
    op.drop_index('uk_user_crawler', table_name='user_crawler_configs')
    op.drop_table('user_crawler_configs')
    op.drop_index('ix_material_comments_id', table_name='material_comments')
    op.drop_table('material_comments')
    op.drop_index('ix_schools_id', table_name='schools')
    op.drop_index('ix_schools_name', table_name='schools')
    op.drop_index('ix_schools_province', table_name='schools')
    op.drop_table('schools')
    op.drop_index('idx_crawl_time', table_name='user_crawler_results')
    op.drop_index('idx_info_type', table_name='user_crawler_results')
    op.drop_index('idx_is_notified', table_name='user_crawler_results')
    op.drop_index('idx_is_read', table_name='user_crawler_results')
    op.drop_index('idx_match_score', table_name='user_crawler_results')
    op.drop_index('idx_user_crawler_id', table_name='user_crawler_results')
    op.drop_index('uk_user_info', table_name='user_crawler_results')
    op.drop_table('user_crawler_results')
    op.drop_index('ix_material_ratings_id', table_name='material_ratings')
    op.drop_table('material_ratings')
    op.drop_index('ix_feedbacks_id', table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index('ix_material_categories_id', table_name='material_categories')
    op.drop_table('material_categories')
    op.drop_table('user_material_favorites')
    op.drop_index('idx_crawl_status', table_name='user_crawler_logs')
    op.drop_index('idx_crawl_time', table_name='user_crawler_logs')
    op.drop_index('idx_user_crawler_id', table_name='user_crawler_logs')
    op.drop_table('user_crawler_logs')
    op.drop_index('ix_user_downloads_id', table_name='user_downloads')
    op.drop_index('ix_user_downloads_material_id', table_name='user_downloads')
    op.drop_index('ix_user_downloads_user_id', table_name='user_downloads')
    op.drop_table('user_downloads')
    op.drop_index('ix_learning_materials_category_id', table_name='learning_materials')
    op.drop_index('ix_learning_materials_id', table_name='learning_materials')
    op.drop_index('ix_learning_materials_subject', table_name='learning_materials')
    op.drop_index('ix_learning_materials_type', table_name='learning_materials')
    op.drop_table('learning_materials')
    op.drop_index('idx_is_active', table_name='user_crawler_keywords')
    op.drop_index('idx_keyword', table_name='user_crawler_keywords')
    op.drop_index('idx_user_crawler_id', table_name='user_crawler_keywords')
    op.drop_index('uk_crawler_keyword', table_name='user_crawler_keywords')
    op.drop_table('user_crawler_keywords')
    op.alter_column('orders', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='订单ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('orders', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('orders', 'product_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='产品ID',
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_comment='价格',
               existing_nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_comment='总金额',
               existing_nullable=False)
    op.alter_column('orders', 'payment_method',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='支付方式: 1-微信支付, 2-支付宝',
               existing_nullable=False)
    op.alter_column('orders', 'payment_status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='支付状态: 0-待支付, 1-已支付, 2-已取消, 3-已退款',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('idx_created_at', table_name='orders')
    op.drop_index('idx_payment_status', table_name='orders')
    op.drop_index('idx_user_id', table_name='orders')
    op.drop_index('uk_trade_no', table_name='orders')
    op.drop_table_comment(
        'orders',
        existing_comment='订单表',
        schema=None
    )
    op.alter_column('products', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='产品ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('products', 'price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_comment='价格',
               existing_nullable=False)
    op.alter_column('products', 'original_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_comment='原价',
               existing_nullable=True)
    op.alter_column('products', 'type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='产品类型: 1-考研VIP, 2-考公VIP, 3-双赛道VIP',
               existing_nullable=False)
    op.alter_column('products', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='状态: 1-上架, 0-下架',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('idx_status', table_name='products')
    op.drop_index('idx_type', table_name='products')
    op.drop_table_comment(
        'products',
        existing_comment='产品/套餐表',
        schema=None
    )
    op.alter_column('push_logs', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='日志ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('push_logs', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('push_logs', 'info_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='信息ID',
               existing_nullable=False)
    op.alter_column('push_logs', 'category',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='分类: 1-考研, 2-考公',
               existing_nullable=False)
    op.alter_column('push_logs', 'push_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='推送类型: 1-微信模板消息, 2-企业微信, 3-短信',
               existing_nullable=False)
    op.alter_column('push_logs', 'push_status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='推送状态: 1-成功, 0-失败',
               existing_nullable=False)
    op.drop_index('idx_info_id', table_name='push_logs')
    op.drop_index('idx_push_status', table_name='push_logs')
    op.drop_index('idx_push_type', table_name='push_logs')
    op.drop_index('idx_user_id', table_name='push_logs')
    op.drop_table_comment(
        'push_logs',
        existing_comment='推送日志表',
        schema=None
    )
    op.alter_column('push_templates', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='模板ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('push_templates', 'type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='推送类型: 1-微信模板消息, 2-企业微信, 3-短信',
               existing_nullable=False)
    op.alter_column('push_templates', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='状态: 1-启用, 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('idx_status', table_name='push_templates')
    op.drop_index('idx_type', table_name='push_templates')
    op.drop_table_comment(
        'push_templates',
        existing_comment='推送模板表',
        schema=None
    )
    op.alter_column('system_config', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='配置ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('system_config', 'config_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='配置类型: 0-字符串, 1-数字, 2-布尔值, 3-JSON',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('system_config', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='状态: 1-启用, 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_table_comment(
        'system_config',
        existing_comment='系统配置表',
        schema=None
    )
    op.alter_column('user_favorites', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='收藏ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_favorites', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_favorites', 'info_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='信息ID',
               existing_nullable=False)
    op.alter_column('user_favorites', 'category',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='分类: 1-考研, 2-考公',
               existing_nullable=False)
    op.drop_index('idx_info_id', table_name='user_favorites')
    op.drop_index('idx_user_id', table_name='user_favorites')
    op.drop_index('uk_user_info', table_name='user_favorites')
    op.drop_table_comment(
        'user_favorites',
        existing_comment='用户收藏信息表',
        schema=None
    )
    op.alter_column('user_keywords', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='关键词ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_keywords', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_keywords', 'category',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='分类: 1-考研, 2-考公',
               existing_nullable=False)
    op.drop_index('idx_category', table_name='user_keywords')
    op.drop_index('idx_user_id', table_name='user_keywords')
    op.drop_index('uk_user_keyword', table_name='user_keywords')
    op.drop_table_comment(
        'user_keywords',
        existing_comment='用户关键词表',
        schema=None
    )
    op.alter_column('user_read_info', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='已读ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_read_info', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_read_info', 'info_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='信息ID',
               existing_nullable=False)
    op.alter_column('user_read_info', 'category',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='分类: 1-考研, 2-考公',
               existing_nullable=False)
    op.drop_index('idx_info_id', table_name='user_read_info')
    op.drop_index('idx_user_id', table_name='user_read_info')
    op.drop_index('uk_user_info', table_name='user_read_info')
    op.drop_table_comment(
        'user_read_info',
        existing_comment='用户已读信息表',
        schema=None
    )
    op.alter_column('user_subscriptions', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='订阅ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_subscriptions', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'subscribe_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='订阅类型: 1-考研, 2-考公, 3-双赛道',
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='订阅状态: 1-有效, 0-无效',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.drop_index('idx_subscribe_type', table_name='user_subscriptions')
    op.drop_index('idx_user_id', table_name='user_subscriptions')
    op.drop_index('uk_user_type', table_name='user_subscriptions')
    op.drop_table_comment(
        'user_subscriptions',
        existing_comment='用户订阅配置表',
        schema=None
    )
    op.add_column('users', sa.Column('need_change_password', sa.Boolean(), nullable=True, comment='是否需要修改密码: 1-是, 0-否'))
    op.alter_column('users', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=True,
               comment='密码（仅管理员用户需要）',
               existing_comment='密码')
    op.alter_column('users', 'gender',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='性别: 0-未知, 1-男, 2-女',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_comment='出生日期',
               existing_nullable=True)
    op.alter_column('users', 'vip_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='VIP类型: 0-非VIP, 1-考研VIP, 2-考公VIP, 3-双赛道VIP',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'trial_status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               existing_comment='试用状态: 0-未试用, 1-试用中, 2-已过期',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_index('idx_created_at', table_name='users')
    op.drop_index('idx_vip_end_time', table_name='users')
    op.drop_index('idx_vip_type', table_name='users')
    op.drop_table_comment(
        'users',
        existing_comment='用户表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '用户表',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_vip_type', 'users', ['vip_type'], unique=False)
    op.create_index('idx_vip_end_time', 'users', ['vip_end_time'], unique=False)
    op.create_index('idx_created_at', 'users', ['created_at'], unique=False)
    op.alter_column('users', 'trial_status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='试用状态: 0-未试用, 1-试用中, 2-已过期',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'vip_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='VIP类型: 0-非VIP, 1-考研VIP, 2-考公VIP, 3-双赛道VIP',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'birthdate',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_comment='出生日期',
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='性别: 0-未知, 1-男, 2-女',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=False,
               comment='密码',
               existing_comment='密码（仅管理员用户需要）')
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='用户ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'need_change_password')
    op.create_table_comment(
        'user_subscriptions',
        '用户订阅配置表',
        existing_comment=None,
        schema=None
    )
    op.create_index('uk_user_type', 'user_subscriptions', ['user_id', 'subscribe_type'], unique=False)
    op.create_index('idx_user_id', 'user_subscriptions', ['user_id'], unique=False)
    op.create_index('idx_subscribe_type', 'user_subscriptions', ['subscribe_type'], unique=False)
    op.alter_column('user_subscriptions', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='订阅状态: 1-有效, 0-无效',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user_subscriptions', 'subscribe_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='订阅类型: 1-考研, 2-考公, 3-双赛道',
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='订阅ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'user_read_info',
        '用户已读信息表',
        existing_comment=None,
        schema=None
    )
    op.create_index('uk_user_info', 'user_read_info', ['user_id', 'info_id', 'category'], unique=False)
    op.create_index('idx_user_id', 'user_read_info', ['user_id'], unique=False)
    op.create_index('idx_info_id', 'user_read_info', ['info_id'], unique=False)
    op.alter_column('user_read_info', 'category',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='分类: 1-考研, 2-考公',
               existing_nullable=False)
    op.alter_column('user_read_info', 'info_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='信息ID',
               existing_nullable=False)
    op.alter_column('user_read_info', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_read_info', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='已读ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'user_keywords',
        '用户关键词表',
        existing_comment=None,
        schema=None
    )
    op.create_index('uk_user_keyword', 'user_keywords', ['user_id', 'keyword', 'category'], unique=False)
    op.create_index('idx_user_id', 'user_keywords', ['user_id'], unique=False)
    op.create_index('idx_category', 'user_keywords', ['category'], unique=False)
    op.alter_column('user_keywords', 'category',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='分类: 1-考研, 2-考公',
               existing_nullable=False)
    op.alter_column('user_keywords', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_keywords', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='关键词ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'user_favorites',
        '用户收藏信息表',
        existing_comment=None,
        schema=None
    )
    op.create_index('uk_user_info', 'user_favorites', ['user_id', 'info_id', 'category'], unique=False)
    op.create_index('idx_user_id', 'user_favorites', ['user_id'], unique=False)
    op.create_index('idx_info_id', 'user_favorites', ['info_id'], unique=False)
    op.alter_column('user_favorites', 'category',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='分类: 1-考研, 2-考公',
               existing_nullable=False)
    op.alter_column('user_favorites', 'info_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='信息ID',
               existing_nullable=False)
    op.alter_column('user_favorites', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_favorites', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='收藏ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'system_config',
        '系统配置表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('system_config', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='状态: 1-启用, 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('system_config', 'config_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='配置类型: 0-字符串, 1-数字, 2-布尔值, 3-JSON',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('system_config', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='配置ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'push_templates',
        '推送模板表',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_type', 'push_templates', ['type'], unique=False)
    op.create_index('idx_status', 'push_templates', ['status'], unique=False)
    op.alter_column('push_templates', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='状态: 1-启用, 0-禁用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('push_templates', 'type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='推送类型: 1-微信模板消息, 2-企业微信, 3-短信',
               existing_nullable=False)
    op.alter_column('push_templates', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='模板ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'push_logs',
        '推送日志表',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_user_id', 'push_logs', ['user_id'], unique=False)
    op.create_index('idx_push_type', 'push_logs', ['push_type'], unique=False)
    op.create_index('idx_push_status', 'push_logs', ['push_status'], unique=False)
    op.create_index('idx_info_id', 'push_logs', ['info_id'], unique=False)
    op.alter_column('push_logs', 'push_status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='推送状态: 1-成功, 0-失败',
               existing_nullable=False)
    op.alter_column('push_logs', 'push_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='推送类型: 1-微信模板消息, 2-企业微信, 3-短信',
               existing_nullable=False)
    op.alter_column('push_logs', 'category',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='分类: 1-考研, 2-考公',
               existing_nullable=False)
    op.alter_column('push_logs', 'info_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='信息ID',
               existing_nullable=False)
    op.alter_column('push_logs', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('push_logs', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='日志ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'products',
        '产品/套餐表',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_type', 'products', ['type'], unique=False)
    op.create_index('idx_status', 'products', ['status'], unique=False)
    op.alter_column('products', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='状态: 1-上架, 0-下架',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('products', 'type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='产品类型: 1-考研VIP, 2-考公VIP, 3-双赛道VIP',
               existing_nullable=False)
    op.alter_column('products', 'original_price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='原价',
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='价格',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='产品ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'orders',
        '订单表',
        existing_comment=None,
        schema=None
    )
    op.create_index('uk_trade_no', 'orders', ['trade_no'], unique=False)
    op.create_index('idx_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('idx_payment_status', 'orders', ['payment_status'], unique=False)
    op.create_index('idx_created_at', 'orders', ['created_at'], unique=False)
    op.alter_column('orders', 'payment_status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='支付状态: 0-待支付, 1-已支付, 2-已取消, 3-已退款',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('orders', 'payment_method',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               existing_comment='支付方式: 1-微信支付, 2-支付宝',
               existing_nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='总金额',
               existing_nullable=False)
    op.alter_column('orders', 'price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='价格',
               existing_nullable=False)
    op.alter_column('orders', 'product_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='产品ID',
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               existing_comment='订单ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_table('user_crawler_keywords',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_crawler_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='用户爬虫配置ID'),
    sa.Column('keyword', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='关键词'),
    sa.Column('keyword_type', mysql.TINYINT(), autoincrement=False, nullable=False, comment='关键词类型: 1=专业, 2=学校, 3=地区, 4=其他'),
    sa.Column('weight', mysql.DECIMAL(precision=3, scale=2), server_default=sa.text("'1.00'"), nullable=True, comment='权重'),
    sa.Column('is_active', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='是否激活'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户爬虫关键词关联表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='用户爬虫关键词关联表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uk_crawler_keyword', 'user_crawler_keywords', ['user_crawler_id', 'keyword', 'keyword_type'], unique=False)
    op.create_index('idx_user_crawler_id', 'user_crawler_keywords', ['user_crawler_id'], unique=False)
    op.create_index('idx_keyword', 'user_crawler_keywords', ['keyword'], unique=False)
    op.create_index('idx_is_active', 'user_crawler_keywords', ['is_active'], unique=False)
    op.create_table('learning_materials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False, comment='资料标题'),
    sa.Column('description', mysql.TEXT(), nullable=False, comment='资料描述'),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料类型：1-考研，2-考公'),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料分类ID'),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=False, comment='科目：如数学、英语、政治等'),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False, comment='文件存储路径'),
    sa.Column('file_url', mysql.VARCHAR(length=255), nullable=False, comment='文件下载URL'),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=False, comment='文件大小，单位：字节'),
    sa.Column('file_extension', mysql.VARCHAR(length=50), nullable=False, comment='文件扩展名'),
    sa.Column('cover_image', mysql.VARCHAR(length=255), nullable=True, comment='封面图片URL'),
    sa.Column('uploader_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='上传者ID'),
    sa.Column('upload_time', mysql.DATETIME(), nullable=False, comment='上传时间'),
    sa.Column('download_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='下载次数'),
    sa.Column('rating', mysql.FLOAT(), nullable=True, comment='评分'),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否有效'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_learning_materials_type', 'learning_materials', ['type'], unique=False)
    op.create_index('ix_learning_materials_subject', 'learning_materials', ['subject'], unique=False)
    op.create_index('ix_learning_materials_id', 'learning_materials', ['id'], unique=False)
    op.create_index('ix_learning_materials_category_id', 'learning_materials', ['category_id'], unique=False)
    op.create_table('user_downloads',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料ID'),
    sa.Column('download_time', mysql.DATETIME(), nullable=False, comment='下载时间'),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True, comment='下载IP地址'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_downloads_user_id', 'user_downloads', ['user_id'], unique=False)
    op.create_index('ix_user_downloads_material_id', 'user_downloads', ['material_id'], unique=False)
    op.create_index('ix_user_downloads_id', 'user_downloads', ['id'], unique=False)
    op.create_table('user_crawler_logs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_crawler_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='用户爬虫配置ID'),
    sa.Column('crawl_status', mysql.TINYINT(), autoincrement=False, nullable=False, comment='爬取状态: 1=成功, 2=失败, 3=部分成功'),
    sa.Column('items_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='爬取到的项目数'),
    sa.Column('new_items_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='新增项目数'),
    sa.Column('error_message', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'), nullable=True, comment='错误信息'),
    sa.Column('crawl_duration', mysql.INTEGER(), autoincrement=False, nullable=True, comment='爬取耗时(秒)'),
    sa.Column('crawl_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户爬虫日志表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='用户爬虫日志表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_user_crawler_id', 'user_crawler_logs', ['user_crawler_id'], unique=False)
    op.create_index('idx_crawl_time', 'user_crawler_logs', ['crawl_time'], unique=False)
    op.create_index('idx_crawl_status', 'user_crawler_logs', ['crawl_status'], unique=False)
    op.create_table('user_material_favorites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.id'], name='user_material_favorites_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_material_favorites_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('material_categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False, comment='分类名称'),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False, comment='适用类型：1-考研，2-考公，3-通用'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='分类描述'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_material_categories_id', 'material_categories', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('type', mysql.ENUM('SUGGESTION', 'PROBLEM', 'OTHER'), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('contact', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'PROCESSED'), nullable=True),
    sa.Column('reply', mysql.TEXT(), nullable=True, comment='管理员回复'),
    sa.Column('reply_at', mysql.DATETIME(), nullable=True, comment='回复时间'),
    sa.Column('is_deleted_by_user', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='用户是否删除'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_feedbacks_id', 'feedbacks', ['id'], unique=False)
    op.create_table('material_ratings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料ID'),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False, comment='评分，1-5星'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_material_ratings_id', 'material_ratings', ['id'], unique=False)
    op.create_table('user_crawler_results',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_crawler_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='用户爬虫配置ID'),
    sa.Column('info_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='信息ID(对应考研或考公信息表)'),
    sa.Column('info_type', mysql.TINYINT(), autoincrement=False, nullable=False, comment='信息类型: 1=考研, 2=考公'),
    sa.Column('match_score', mysql.DECIMAL(precision=5, scale=2), server_default=sa.text("'0.00'"), nullable=True, comment='匹配分数'),
    sa.Column('is_read', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已读: 0=未读, 1=已读'),
    sa.Column('is_notified', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已通知: 0=未通知, 1=已通知'),
    sa.Column('is_favorite', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否收藏: 0=未收藏, 1=已收藏'),
    sa.Column('crawl_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户爬虫结果表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='用户爬虫结果表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uk_user_info', 'user_crawler_results', ['user_crawler_id', 'info_id'], unique=False)
    op.create_index('idx_user_crawler_id', 'user_crawler_results', ['user_crawler_id'], unique=False)
    op.create_index('idx_match_score', 'user_crawler_results', ['match_score'], unique=False)
    op.create_index('idx_is_read', 'user_crawler_results', ['is_read'], unique=False)
    op.create_index('idx_is_notified', 'user_crawler_results', ['is_notified'], unique=False)
    op.create_index('idx_info_type', 'user_crawler_results', ['info_type'], unique=False)
    op.create_index('idx_crawl_time', 'user_crawler_results', ['crawl_time'], unique=False)
    op.create_table('schools',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('province', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('has_master', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_schools_province', 'schools', ['province'], unique=False)
    op.create_index('ix_schools_name', 'schools', ['name'], unique=False)
    op.create_index('ix_schools_id', 'schools', ['id'], unique=False)
    op.create_table('material_comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料ID'),
    sa.Column('comment', mysql.TEXT(), nullable=False, comment='评论内容'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('parent_comment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['material_comments.id'], name='material_comments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_material_comments_id', 'material_comments', ['id'], unique=False)
    op.create_table('user_crawler_configs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('crawler_type', mysql.TINYINT(), autoincrement=False, nullable=False, comment='爬虫类型: 1=考研, 2=考公'),
    sa.Column('crawler_name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=100), nullable=False, comment='爬虫名称'),
    sa.Column('base_crawler_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True, comment='基础爬虫ID'),
    sa.Column('config_json', mysql.JSON(), nullable=False, comment='爬虫配置JSON'),
    sa.Column('status', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态: 1=激活, 0=暂停'),
    sa.Column('priority', mysql.TINYINT(), server_default=sa.text("'2'"), autoincrement=False, nullable=False, comment='优先级: 1=高, 2=中, 3=低'),
    sa.Column('last_crawl_time', mysql.DATETIME(), nullable=True, comment='最后爬取时间'),
    sa.Column('crawl_interval', mysql.INTEGER(), server_default=sa.text("'3600'"), autoincrement=False, nullable=False, comment='爬取间隔(秒)'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户爬虫配置表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='用户爬虫配置表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('uk_user_crawler', 'user_crawler_configs', ['user_id', 'crawler_name'], unique=False)
    op.create_index('idx_user_id', 'user_crawler_configs', ['user_id'], unique=False)
    op.create_index('idx_status', 'user_crawler_configs', ['status'], unique=False)
    op.create_index('idx_crawler_type', 'user_crawler_configs', ['crawler_type'], unique=False)
    # ### end Alembic commands ###
