"""添加read字段到push_logs表

Revision ID: b272d52f2f32
Revises: 7b2d43f224c1
Create Date: 2026-04-22 14:34:45.629077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b272d52f2f32'
down_revision: Union[str, None] = '7b2d43f224c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_logs', sa.Column('read', sa.Boolean(), nullable=True, comment='是否已读: 1-是, 0-否'))
    # 设置默认值为False
    op.execute("UPDATE push_logs SET `read` = FALSE WHERE `read` IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_logs', 'read')
    op.create_table('user_material_favorites',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料ID'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='收藏时间'),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.id'], name='user_material_favorites_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_material_favorites_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_material_favorites_user_id', 'user_material_favorites', ['user_id'], unique=False)
    op.create_index('ix_user_material_favorites_material_id', 'user_material_favorites', ['material_id'], unique=False)
    op.create_index('ix_user_material_favorites_id', 'user_material_favorites', ['id'], unique=False)
    op.create_table('material_ratings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料ID'),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False, comment='评分，1-5星'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.id'], name='material_ratings_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='material_ratings_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_material_ratings_id', 'material_ratings', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('type', mysql.ENUM('SUGGESTION', 'PROBLEM', 'OTHER'), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('contact', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'PROCESSED'), nullable=True),
    sa.Column('reply', mysql.TEXT(), nullable=True, comment='管理员回复'),
    sa.Column('reply_at', mysql.DATETIME(), nullable=True, comment='回复时间'),
    sa.Column('is_deleted_by_user', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='用户是否删除'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_feedbacks_id', 'feedbacks', ['id'], unique=False)
    op.create_table('material_categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False, comment='分类名称'),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False, comment='适用类型：1-考研，2-考公，3-通用'),
    sa.Column('description', mysql.TEXT(), nullable=True, comment='分类描述'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_material_categories_id', 'material_categories', ['id'], unique=False)
    op.create_table('learning_materials',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False, comment='资料标题'),
    sa.Column('description', mysql.TEXT(), nullable=False, comment='资料描述'),
    sa.Column('type', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料类型：1-考研，2-考公'),
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料分类ID'),
    sa.Column('subject', mysql.VARCHAR(length=100), nullable=False, comment='科目：如数学、英语、政治等'),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False, comment='文件存储路径'),
    sa.Column('file_url', mysql.VARCHAR(length=255), nullable=False, comment='文件下载URL'),
    sa.Column('file_size', mysql.INTEGER(), autoincrement=False, nullable=False, comment='文件大小，单位：字节'),
    sa.Column('file_extension', mysql.VARCHAR(length=50), nullable=False, comment='文件扩展名'),
    sa.Column('cover_image', mysql.VARCHAR(length=255), nullable=True, comment='封面图片URL'),
    sa.Column('uploader_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='上传者ID'),
    sa.Column('upload_time', mysql.DATETIME(), nullable=False, comment='上传时间'),
    sa.Column('download_count', mysql.INTEGER(), autoincrement=False, nullable=True, comment='下载次数'),
    sa.Column('rating', mysql.FLOAT(), nullable=True, comment='评分'),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否有效'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['category_id'], ['material_categories.id'], name='learning_materials_ibfk_1'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name='learning_materials_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_learning_materials_type', 'learning_materials', ['type'], unique=False)
    op.create_index('ix_learning_materials_subject', 'learning_materials', ['subject'], unique=False)
    op.create_index('ix_learning_materials_id', 'learning_materials', ['id'], unique=False)
    op.create_index('ix_learning_materials_category_id', 'learning_materials', ['category_id'], unique=False)
    op.create_table('material_comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料ID'),
    sa.Column('parent_comment_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='父评论ID（回复功能）'),
    sa.Column('comment', mysql.TEXT(), nullable=False, comment='评论内容'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.id'], name='material_comments_ibfk_2'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['material_comments.id'], name='material_comments_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='material_comments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_material_comments_id', 'material_comments', ['id'], unique=False)
    op.create_table('user_downloads',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='用户ID'),
    sa.Column('material_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='资料ID'),
    sa.Column('download_time', mysql.DATETIME(), nullable=False, comment='下载时间'),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=True, comment='下载IP地址'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['material_id'], ['learning_materials.id'], name='user_downloads_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_downloads_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_downloads_user_id', 'user_downloads', ['user_id'], unique=False)
    op.create_index('ix_user_downloads_material_id', 'user_downloads', ['material_id'], unique=False)
    op.create_index('ix_user_downloads_id', 'user_downloads', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('province', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('has_master', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_schools_province', 'schools', ['province'], unique=False)
    op.create_index('ix_schools_name', 'schools', ['name'], unique=False)
    op.create_index('ix_schools_id', 'schools', ['id'], unique=False)
    # ### end Alembic commands ###
